version: '3.8'

services:
  commerzbank-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: commerzbank-app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=file:./prisma/dev.db
      - ADMIN_PASSWORD=COMMTAN@123
    volumes:
      # Persist database
      - ./backend/prisma:/app/prisma
      # Persist uploads
      - ./backend/uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a separate database service if you want to use PostgreSQL
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: commerzbank-postgres
  #   environment:
  #     POSTGRES_DB: commerzbank
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

# volumes:
#   postgres_data:


